# Generated by Django 4.2.4 on 2023-08-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('words', models.CharField(max_length=100)),
                ('weights', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
    ]
