# Generated by Django 4.2.4 on 2023-08-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': True},
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 75c32d966ac65d5fc7bc9da71943e510d23aec00
