# Generated by Django 4.2.4 on 2023-08-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_alter_keyword_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 75c32d966ac65d5fc7bc9da71943e510d23aec00
