# Generated by Django 4.2.4 on 2023-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_alter_keyword_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 75c32d966ac65d5fc7bc9da71943e510d23aec00
