# Generated by Django 3.2.20 on 2023-08-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=300)),
                ('media_count', models.IntegerField()),
                ('follows_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
            ],
        ),
    ]
