# Generated by Django 3.2.20 on 2023-08-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_influencer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_10_12_16yp',
            fields=[
                ('post_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('caption', models.TextField(max_length=10000)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('media_type', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'post_10_12_16yp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post_b_saem',
            fields=[
                ('post_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('caption', models.TextField(max_length=10000)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('media_type', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'post_b.saem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post_limmiae',
            fields=[
                ('post_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('caption', models.TextField(max_length=10000)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('media_type', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'post_limmiae',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post_vevi_d_live',
            fields=[
                ('post_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('caption', models.TextField(max_length=10000)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('media_type', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'post_vevi_d_live',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post_wescsp1121',
            fields=[
                ('post_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('caption', models.TextField(max_length=10000)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('media_type', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'post_wescsp1121',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post_yakstory119',
            fields=[
                ('post_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('caption', models.TextField(max_length=10000)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('media_type', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'post_yakstory119',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='influencer',
            table='influencers',
        ),
    ]
