# Generated by Django 3.2.20 on 2023-08-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post_iam_yaksa_post_pt_jjuny_post_yakstagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_adv',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('bussiness', models.CharField(max_length=100)),
                ('followers_count', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_adv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_influ',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('instagram_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('bussiness', models.CharField(max_length=100)),
                ('followers_count', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_influ',
                'managed': False,
            },
        ),
    ]
