# Generated by Django 3.2.20 on 2023-08-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_adv_user_influ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_master',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('post_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('caption', models.TextField(max_length=10000)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('media_type', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'post_master',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Post_limmiae',
        ),
    ]