# Generated by Django 4.2.4 on 2023-08-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hot_post',
            fields=[
                ('post_id', models.CharField(max_length=100)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('insta_url', models.CharField(max_length=1000)),
                ('post_url', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hot_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Influencer_average',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_average', models.IntegerField()),
                ('comments_average', models.IntegerField()),
                ('followers_average', models.IntegerField()),
                ('post_average', models.IntegerField()),
                ('advpost_average', models.IntegerField()),
                ('week_post_avg', models.IntegerField()),
                ('number', models.IntegerField()),
                ('ave_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'influencer_average',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('marketing_content', models.TextField()),
                ('media_channels', models.TextField()),
                ('subtitle', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('content_1', models.TextField()),
                ('sub_content_1', models.TextField()),
                ('content_2', models.TextField()),
                ('sub_content_2', models.TextField()),
            ],
            options={
                'db_table': 'Recruitment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecruitmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recruitment_images/')),
                ('is_profile', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'RecruitmentImage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supply_influencer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=100)),
                ('reason_supply', models.TextField(max_length=10000)),
            ],
            options={
                'db_table': 'supply_influencer',
                'managed': False,
            },
        ),
    ]
