# Generated by Django 4.2.4 on 2023-08-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yourmodel',
            old_name='content',
            new_name='body',
        ),
    ]
