# Generated by Django 4.2.4 on 2023-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_content_yourmodel_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=300)),
                ('media_count', models.IntegerField()),
                ('follows_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('adv_count', models.IntegerField()),
                ('week_avg_post', models.DecimalField(decimal_places=1, max_digits=5)),
                ('am_pm', models.CharField(max_length=100)),
                ('avg_post_time', models.CharField(max_length=100)),
                ('feed_percent', models.IntegerField()),
                ('reels_percent', models.IntegerField()),
                ('avg_comments', models.IntegerField()),
                ('avg_goods', models.IntegerField()),
                ('comments_percent', models.IntegerField()),
                ('goods_percent', models.IntegerField()),
            ],
            options={
                'db_table': 'influencers',
                'managed': False,
            },
        ),
    ]
