# Generated by Django 4.2.4 on 2023-08-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_influencer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Influencer',
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 75c32d966ac65d5fc7bc9da71943e510d23aec00
