# Generated by Django 4.2.4 on 2023-08-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_influencer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_count', models.IntegerField()),
                ('like_count', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('post_url', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'hot_post',
                'managed': False,
            },
        ),
    ]
