# Generated by Django 3.2.20 on 2023-08-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recruitment_recruitmentimage'),
        ('main', '0004_delete_influencer'),
    ]

    operations = [
    ]
