# Generated by Django 3.2.20 on 2023-08-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20230821_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.AlterModelTable(
            name='recruitmentimage',
            table='Recruitmentimage',
        ),
    ]
