# Generated by Django 3.2.20 on 2023-08-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230821_0843'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recruitmentimage',
            table='RecruitmentImage',
        ),
    ]