# Generated by Django 3.2.20 on 2023-08-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_recruitmentimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recruitmentimage',
            table='Recruitmentimage',
        ),
    ]
