# Generated by Django 3.2.20 on 2023-08-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_recruitmentimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recruitmentimage',
            table='RecruitmentImage',
        ),
    ]